import React, { useEffect, useRef, useState } from 'react';
import { X, Upload, ClipboardPaste } from 'lucide-react';
import { importResumeFromFile, parseResumeJson } from '../utils/importExport.js';
import { putResume } from '../db/resumesDb.js';

export default function ImportModal({ onClose, onImported }) {
  const [tab, setTab] = useState('paste'); // 'paste' | 'file'
  const [text, setText] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const textareaRef = useRef(null);

  useEffect(() => {
    function onKey(e) { if (e.key === 'Escape') onClose(); }
    document.addEventListener('keydown', onKey);
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', onKey);
      document.body.style.overflow = prev;
    };
  }, [onClose]);

  useEffect(() => {
    if (tab === 'paste') setTimeout(() => textareaRef.current?.focus(), 50);
  }, [tab]);

  async function handlePasteImport() {
    if (!text.trim()) { setError('Paste your JSON first.'); return; }
    setBusy(true);
    setError('');
    try {
      const doc = parseResumeJson(text.trim());
      await putResume(doc);
      onImported();
      onClose();
    } catch (err) {
      setError(err.message);
    } finally {
      setBusy(false);
    }
  }

  async function handleFileImport() {
    setBusy(true);
    setError('');
    try {
      const doc = await importResumeFromFile();
      if (!doc) { setBusy(false); return; }
      await putResume(doc);
      onImported();
      onClose();
    } catch (err) {
      setError(err.message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="new-resume-backdrop" onClick={onClose}>
      <div className="import-modal" onClick={e => e.stopPropagation()}>
        <button className="new-resume-close" onClick={onClose} aria-label="Close">
          <X size={20} />
        </button>

        <header className="new-resume-header">
          <h2>Import resume</h2>
          <p>Paste JSON from your AI or choose a file.</p>
        </header>

        <div className="import-tabs">
          <button
            className={`import-tab ${tab === 'paste' ? 'active' : ''}`}
            onClick={() => setTab('paste')}
          >
            <ClipboardPaste size={14} /> Paste JSON
          </button>
          <button
            className={`import-tab ${tab === 'file' ? 'active' : ''}`}
            onClick={() => setTab('file')}
          >
            <Upload size={14} /> From file
          </button>
        </div>

        {tab === 'paste' ? (
          <div className="import-paste-wrap">
            <textarea
              ref={textareaRef}
              className="import-textarea"
              value={text}
              onChange={e => { setText(e.target.value); setError(''); }}
              placeholder='{ "name": "My Resume", "template": "classic-clear", ... }'
              spellCheck={false}
            />
            {error && <div className="import-error">{error}</div>}
            <button
              className="import-submit-btn"
              onClick={handlePasteImport}
              disabled={busy}
            >
              {busy ? 'Importing...' : 'Import'}
            </button>
          </div>
        ) : (
          <div className="import-file-wrap">
            <p className="import-file-hint">Select a <code>.json</code> file exported from Resuflow or generated by an AI.</p>
            {error && <div className="import-error">{error}</div>}
            <button
              className="import-submit-btn"
              onClick={handleFileImport}
              disabled={busy}
            >
              <Upload size={14} />
              {busy ? 'Importing...' : 'Choose file'}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
